site_name: Aincrad Codex
site_description: Documentation blessed by Solar Khan and Lilith.Aethra
site_author: Aincrad Devs
site_url: https://Aincrad.SolarKhan.github.io

repo_name: yourusername/aincrad
repo_url: https://github.com/yourusername/aincrad
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

nav:
  - Home: index.md
  - Divine Law: COVENANT.md
  - API Reference: api/README.md
