name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [main, develop]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/pages.yml'
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
  schedule:
    # Weekly build to catch dependency updates
    - cron: '0 0 * * 0'

# Cancel previous runs for the same PR/branch
concurrency:
  group: pages-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Default environment variables
env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '20'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Cache Python dependencies
      uses: actions/cache@v4
      id: pip-cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/mkdocs.yml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r docs/requirements.txt || \
          pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-minify-plugin

    - name: Build documentation
      run: |
        mkdir -p site
        mkdocs build --strict --verbose --site-dir site

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz
        
    - name: Generate API documentation
      run: |
        mkdir -p site/api
        doxygen docs/Doxyfile
        cp -r docs/doxygen/html/* site/api/

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./site

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4